inputs:
  test-case:
    description: String
    required: true
  test:
    description: String
    required: false
runs:
  using: composite
  steps:
  - shell: bash
    run: |
      : call2-node check env
      echo 'console.log("call2-node: "+JSON.stringify(process.env))'|node
  - uses: ./call-node
    with:
      test: ${{ inputs.test-case }}
      something: ${{ inputs.test }}
    env:
      INPUT_TEST: 7
